### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by ImMello223** [Harry-Pan/OwOHP-Typecho#1]
1. 点击后台“重建索引”后会跳转到https://链接/OwOHP?action=rebuild （404界面）🧐
2.  Plugin.php 178行 pluginUrl('/OwOHP/owo/OwOHP.json'); ?>，在这个文件夹下没有json，大概率是写错了吧😁

**Comment by Harry-Pan** [comment]
已记录，待我择吉日修复

**Comment by Harry-Pan** [comment]
问题已修复
